name:                google-location-history-converter
version:             0.4.0.0
github:              "rickprice/google-location-history-converter"
license:             BSD-3-Clause
author:              "Frederick Price"
maintainer:          "fprice@pricemail.ca"
copyright:           "BSD-3-Clause"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Command line utility to convert Google Takeout Location data to KML format
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rickprice/google-location-history-converter#readme>

dependencies:
- aeson >=2.0 && <2.3
- base >=4.7 && <4.20
- bytestring >=0.10 && <0.13
- formatting >=7.1 && <7.3
- json-stream >=0.4 && <0.5
- neat-interpolation >=0.5 && <0.6
- optparse-applicative >=0.16 && <0.19
- string-conversions >= 0.4 && <0.5
- tar >=0.5.1.1 && <0.6
- text >= 1.2 && <2.2
- time >=1.9 && <1.13
- zlib >=0.6.3.0 && <0.7
- scientific >=0.3.7.0 && <0.3.8
- relude

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
# These are needed for Stan
- -fwrite-ide-info
- -hiedir=.hie

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  glconverter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - google-location-history-converter

tests:
  google-location-history-converter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec >=2.8 && <2.12
    - google-location-history-converter
